### ISSUE TITLE
Where to download Geogrid data

### ISSUE THREAD

**Issue by jia-11** [Toberumono/WRF-Setup-Script#1]
Hi! This script is very helpful. But I cannot find the geogrid data in the provided link (http://www2.mmm.ucar.edu/wrf/users/download/get_source.html).May I know where to get the file?

**Comment by Toberumono** [comment]
On the page that you downloaded the WPS code, you should (if you scroll down a bit) see this.
![image](https://cloud.githubusercontent.com/assets/1240174/11113563/9237390e-88e3-11e5-8ad4-12367d91f7ce.png)
Click on the “here” link in the text below the table.  You’ll probably want the complete dataset even though it is a bit bigger.
