### ISSUE TITLE
Compile wrf-chem?

### ISSUE THREAD

**Issue by lovechang1986** [Toberumono/WRF-Setup-Script#4]
Whether wrf-chem is completed when I complete the WRF installation？

**Comment by Toberumono** [comment]
@lovechang1986 wrf-chem should be compiled along with the rest of WRF. If this is not happening, could you send me the version of WRF that you are using and any errors output to the console?

**Comment by lovechang1986** [comment]
I don't know, I just have this question. So how do I check the installation of wrf-chem?

**Comment by Toberumono** [comment]
From within the WRFV3 directory (it is created as part of the setup process), run `ls -ls main/*.exe`. You should see, ndown.exe, real.exe, and wrf.exe.
